services:
  backoffice:
    build:
      context: ./
    restart: always
    networks:
      - traefik-public
      - default
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      - TZ=${TZ?"Europe/Moscow"}
      - DOMAIN=${DOMAIN}
      - FRONTEND_HOST=${FRONTEND_HOST?Variable not set}
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - DB_1C=${DB_1C}
      - DWH_DB_DRIVER=${DWH_DB_DRIVER}
      - DWH_DB_HOST=${DWH_DB_HOST}
      - DWH_DB_NAME=${DWH_DB_NAME}
      - DWH_DB_USER=${DWH_DB_USER}
      - DWH_DB_PASS=${DWH_DB_PASS}
      - AWS_ENDPOINT=${AWS_ENDPOINT}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - ONE_C_USER=${ONE_C_USER}
      - ONE_C_PASSWORD=${ONE_C_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.services.${STACK_NAME?Variable not set}-backoffice.loadbalancer.server.port=8000
      - traefik.http.routers.${STACK_NAME?Variable not set}-backoffice-http.rule=Host(`api.${DOMAIN?Variable not set}`)
      - traefik.http.routers.${STACK_NAME?Variable not set}-backoffice-http.entrypoints=http

  db:
    image: postgres:12
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - backoffice_pg_data:/var/lib/postgresql/data/pgdata
    environment:
      - TZ="Europe/Moscow"
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}

  adminer:
    image: adminer
    restart: always
    networks:
      - traefik-public
      - default
    depends_on:
      - db
    # environment:
    #   - ADMINER_DESIGN=pepa-linha-dark
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.routers.${STACK_NAME?Variable not set}-adminer-http.rule=Host(`adminer.${DOMAIN?Variable not set}`)
      - traefik.http.routers.${STACK_NAME?Variable not set}-adminer-http.entrypoints=http
      - traefik.http.services.${STACK_NAME?Variable not set}-adminer.loadbalancer.server.port=8080


volumes:
  backoffice_pg_data:

networks:
  traefik-public:
    external: true